In [2]:
# Importing important Libraries.

import tensorflow as tf
import numpy as np


In [14]:
# Helloworld program using Tensorflow in 'v1'.

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

var = tf.constant("Hello_World")

sess = tf.compat.v1.Session()
print(sess.run(var))
sess.close

b'Hello_World'


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7fab7b48df90>>

In [17]:
# Helloworld program using Tensorflow in 'v1' without close method.

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

variable = tf.constant('Hello-World')

with tf.compat.v1.Session() as sess:
  print(sess.run(variable))

b'Hello-World'


In [22]:
# Multiplying two numbers here.

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

variable_1 = tf.constant(2)
variable_2 = tf.constant(5)

sess = tf.compat.v1.Session()
print(sess.run(variable_1 * variable_2))
sess.close

10


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7fab7b556590>>

In [23]:
# Adding three numbers using Tensorflow 'v1'.

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

first_number = tf.constant(5)
second_number = tf.constant(10)
third_number = tf.constant(15)

with tf.compat.v1.Session() as sess:
  print(sess.run(first_number + second_number + third_number))

30


In [24]:
# Creating a 5*5 matrix which contain value of 10.

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

matrix = tf.fill((5,5), 10)

sess = tf.compat.v1.Session()
print(sess.run(matrix))
sess.close

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7fab7ac1b190>>