In [1]:
# Importing important Libraries

import numpy as np
import tensorflow as tf

In [2]:
# Helloworld program here.

variable = tf.constant("Welcome to Helloworld Program")
print(variable)

tf.Tensor(b'Welcome to Helloworld Program', shape=(), dtype=string)


In [3]:
# Multiplying two numbers with each other.

first_number = tf.constant(6)
second_number = tf.constant(7)

print(first_number * second_number)

tf.Tensor(42, shape=(), dtype=int32)


In [4]:
# Addition of given number.

num1 = tf.constant(5)
num2 = tf.constant(10)
num3 = tf.constant(6)
num4 = tf.constant(4)

print('First number is 5')
print('Second number is 10')
print('Third number is 6')
print('Fourth number is 4')
print('Sum of given number is:', num1+num2+num3+num4)

First number is 5
Second number is 10
Third number is 6
Fourth number is 4
Sum of given number is: tf.Tensor(25, shape=(), dtype=int32)


In [5]:
# Create a Matrix of 5*5 where value should be 9.

matrix = tf.fill((5,5), 9)

print(matrix)

tf.Tensor(
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]], shape=(5, 5), dtype=int32)


In [6]:
# Create a Matrix of 7*7 using zeros on it.

Matrix = tf.zeros((7,7))

print(Matrix)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]], shape=(7, 7), dtype=float32)
